### ISSUE TITLE
[FE] 키워드 검색 관련 기능

### ISSUE THREAD

**Issue by leesungbin** [boostcampwm-2022/web18-PRV#115]
## 이슈 내용
- 위아래로 이동 후에는 키워드로 검색할 수 없습니다.
  - 키워드 검색 후, 논문을 키보드로 선택 했을 때, 엔터를 누르면 선택된 논문 페이지로 이동합니다.

## 기대 결과
- esc를 누르면 검색창을 닫아준다?
- 키보드로 선택 했다가 맨 위로 올린 후, 엔터를 누르면 키워드 검색페이지로 이동한다?

**Comment by Palwol** [comment]
구글은 위아래로 이동하는 범위에 검색창도 들어있네요. 자동완성 선택했다가 다시 맨 위로 올라오면 검색창이 포커싱됩니다. 이렇게 수정해봐도 좋을 것 같아요.
![구글 자동완성](https://user-images.githubusercontent.com/50133823/207019274-fc7c07b9-aff3-4c3d-ac71-70766e629751.gif)
