### ISSUE TITLE
[FE] font 반복 재요청

### ISSUE THREAD

**Issue by yeynii** [boostcampwm-2022/web18-PRV#16]
## 이슈 내용
styled-component 컴포넌트에서 font-face로 정의한 times-new-roman 폰트를 재요청하는 문제가 발생합니다.

## 기대 결과
- 폰트는 최초 1회만 요청되게 합니다.

## 실행화면
https://app.birdeatsbug.com/workspaces/9f64d07b-43bf-46fc-9654-00b047a941c6/collections/c4261afc-d5dc-4e1a-91df-c7eec2bc3ae0/sessions/YlFT41_eyraJT6CI_Fem0_AhSt5aZtJkmhht0Ea6WiR5?networkPane=active

**Comment by Palwol** [comment]
동일한 이슈를 찾았네요!
cdn 링크로 넣거나, font url을 사용하면 될듯 합니다.
이미 찾으셨을수도 있지만 time new roman 폰트 링크 공유드립니다~
https://www.cdnfonts.com/times-new-roman.font

**Comment by Palwol** [comment]
conflict 날수도 있으니 제 코드에서는 수정 안할게욥

**Comment by yeynii** [comment]
와우 짱입니다.. 갓미림..
찾아보니까 styled-component 문제인 듯 하네요.
```
styled-components createGlobalStyle을 통하여 style 초기화, font를 정의한다.
styled-components는 새로운 스타일이 render 될 때마다, <style>태그를 변경 한다.
<style> 태그안에 폰트 정의가 함께 있어 새로운 스타일이 등장할 때마다, font를 재요청한다.
이 재요청 문제로 깜빡거리는 문제가 발생 되고, 유저들은 font style 정의를 분리해달라고 요청했다.
하지만, 개발자는 바빴고, 해당 문제는 그렇게 해결 되지 않은채 약 2년이 흘렀다.
```
라는 내용이 있군요....
https://github.com/styled-components/styled-components/issues/1593
