### ISSUE TITLE
[BE] Docker Build 속도를 빠르게 하기(cache)

### ISSUE THREAD

**Issue by leesungbin** [boostcampwm-2022/web18-PRV#22]
## 이슈 내용
GitHub action에는 자체적으로 cache 가 있으나, Docker에서는 이를 활용하기가 참 어렵습니다.
`npm i` 할 경우, caching 되었던 내용을 사용하게 된다면, 빌드속도가 훨씬 빨라지겠죠?
테스트해보니, 4~5분 정도 걸리는 배포작업이 1분정도로 마무리할 수 있었습니다.
```yml
cache-from: type=gha
cache-to: type=gha
```
위와 같이 옵션을 줄 경우, github에 cache가 잘 되지만, 1개의 빌드에 대해서만 되곤합니다.
즉, BE 이미지에 대해 캐싱되면, FE 이미지에 대해서는 캐싱이 진행되지가 않네요.

## 기대 결과
- fe, be의 이미지가 registry에 캐싱되어, 빌드 속도를 증가시킨다.

**Comment by leesungbin** [comment]
registry에 캐싱 및 FE/BE 배포가 병렬적으로 처리되게 하면 훨씬 빨라지는것을 확인했습니다... 
CI/CD의 세계는 정말 너무 어렵네요.

**Comment by Palwol** [comment]
멋집니다!!!

**Comment by leesungbin** [comment]
참고한 내용들
* [docker 캐싱 관련 stackoverflow](https://stackoverflow.com/questions/71348621/docker-re-use-container-image-by-caching)
* [docker/build-push-action](https://github.com/docker/build-push-action#customizing)
* [Github actions 에서 도커 캐시 적용하기](https://keyhyuk-kim.medium.com/github-actions-%EC%97%90%EC%84%9C-%EB%8F%84%EC%BB%A4-%EC%BA%90%EC%8B%9C-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0-6f1f5d5b1f62)

**Comment by leesungbin** [comment]
* 배포 희망편
![image](https://user-images.githubusercontent.com/25934842/202228246-529b3561-ae74-4505-85c1-d65eaa697cfa.png)
