### ISSUE TITLE
자동완성 목록 - 제목이 없는 경우의 UI

### ISSUE THREAD

**Issue by leesungbin** [boostcampwm-2022/web18-PRV#33]
## 이슈 내용
title, author가 모두 없는 논문에 대해서는 서버에서 결과가 필터링 되고 있다.
title이 없고 author만 있는 경우는 author만 표시되는데, 이에 대한 회의 필요

## 기대 결과
- 

## 스크린샷
-

**Comment by yeynii** [comment]
title이 있는 결과만 보여주게끔 결정
