### ISSUE TITLE
[FE] 키워드 강조 로직에 대한 논의 필요

### ISSUE THREAD

**Issue by leesungbin** [boostcampwm-2022/web18-PRV#40]
## 이슈 내용
![image](https://user-images.githubusercontent.com/25934842/202957850-370c0923-53ab-4282-b183-fc951f963328.png)
`highlight test` 로 검색했을 때, 해당 단어가 전체적으로 다 포함되어있지 않으면, 강조가 되어 있지 않은데,
공백을 기준으로 해당 단어가 결과에 포함되어있는지를 확인하여 highlight를 적용해야 되어야할까요?
* #32 와 관련있는 것 같습니다.

## 기대 결과
-

**Comment by yeynii** [comment]
그러네요. 논의가 필요하겠지만 UX측면에서 단어별로 split해서 higlight 해주는게 훨씬 좋아보이네요.
