### ISSUE TITLE
[FE, BE] authors가 빈배열로 리턴되는 에러

### ISSUE THREAD

**Issue by yeynii** [boostcampwm-2022/web18-PRV#45]
## 이슈 내용
특정 키워드(ex. south korea) 검색시 author이 빈 배열로 리턴되어 에러가 발생합니다.

## 기대 결과
- authors가 빈배열이 되지 않도록 예외처리가 되어야 합니다.

## 스크린샷
![image](https://user-images.githubusercontent.com/30085476/203030947-011a8207-20f8-486f-adcd-2d07a52958b0.png)
![image](https://user-images.githubusercontent.com/30085476/203030869-9782a3ad-53d9-4019-83ad-902eacb58427.png)

**Comment by yeynii** [comment]
- FE
  빈 배열이 들어온 경우를 클라이언트측에서도 예외처리 해주는것이 좋아보입니다.

- BE
  author 객체의 구조가 `{ family, given, .. }` 뿐 아니라 `{ name, .. }` 인 경우도 처리를 해주어야합니다.

**Comment by leesungbin** [comment]
api docs를 참고해보니 author의 형태가 참으로 다이나믹합니다.
```json
"author": [
  {
    "ORCID": "string",
    "suffix": "string",
    "given": "string",
    "family": "string",
    "affiliation": [
      {
        "name": "string"
      }
    ],
    "name": "string",
    "authenticated-orcid": true,
    "prefix": "string",
    "sequence": "string"
  }
],
```

given, family, name 이외에도 고려해야할 내용이 있을까요?
