### ISSUE TITLE
auto-complete나 search api 호출 시 간헐적으로 ERR_CONNECTION_REFUSED 오류가 발생하는 현상

### ISSUE THREAD

**Issue by Palwol** [boostcampwm-2022/web18-PRV#74]
## 이슈 내용
- 아래와 같이 auto-complete이나 search api를 호출할 때 간헐적으로 ERR_CONNECTION_REFUSED 오류가 발생합니다. 
<img width="457" alt="image" src="https://user-images.githubusercontent.com/50133823/204200616-5f41e290-e14f-4df0-9bbd-2e0612a9c53c.png">

- 오류가 발생해도 응답은 잘 도착합니다.

## 기대 결과
- 오류 원인 파악 및 해결

**Comment by leesungbin** [comment]
![image](https://user-images.githubusercontent.com/25934842/204203143-b4cbc3cf-7672-41fe-b3ae-ac0885f73ff1.png)
elasticsearch에서 나는 오류로 확인됩니다.

**Comment by leesungbin** [comment]
* #82 에서 해결되었습니다.
