### ISSUE TITLE
[BE] 논문 상세 정보 호출 시 doi가 입력되지 않은 경우 에러가 발생하지 않음

### ISSUE THREAD

**Issue by Palwol** [boostcampwm-2022/web18-PRV#84]
## 이슈 내용
논문 상세 정보 (/search/paper) 호출 시 query에 doi가 입력되지 않으면 400 에러가 발생할 것으로 기대되지만, 실제로는 에러가 발생하지 않고 undefined를 반환합니다.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/50133823/205102909-d34bd890-7adb-418e-b189-455e806db292.png">

## 기대 결과
논문 상세 정보 호출 시 doi가 입력되지 않으면 400 에러 반환

**Comment by leesungbin** [comment]
`http://49.50.172.204:4000/search?doi=` 로 요청을 보내보면, 
```json
{
  "statusCode": 400,
  "message": [
    "keyword must be longer than or equal to 2 characters",
    "keyword must be a string"
  ],
  "error": "Bad Request"
}
```
와 같은 에러가 나오긴 하는데, 코드를 한번 살펴봐야겠네요.

**Comment by leesungbin** [comment]
![image](https://user-images.githubusercontent.com/25934842/205855037-68887d0e-e297-4c22-a0cc-0fda848322d7.png)
`refetch` 를 수동으로 하니까 400이 뜨는 상황이네요.

**Comment by leesungbin** [comment]
https://github.com/boostcampwm-2022/web18-PRV/blob/0304c63a888082f6266cbbd55b4ca803b5cc721b/frontend/src/pages/PaperDetail/PaperDetail.tsx#L35

이 부분을 지우니, 원하던 결과가 나오네요.
doi가 없을 때, enabled가 false여서 refetch를 안하는 모양입니다.

**Comment by Palwol** [comment]
doi가 비어있으면 쿼리가 동작하지 않아서 에러가 발생하지 않았던 거군요!
확인 감사합니다. 수정하겠습니다.
